[package]
name = "plugin-os-themes"
version = "0.19.1"
edition = "2021"

[dependencies]
anyhow = "1"
serde_json.workspace = true
qol-plugin-daemon.workspace = true
qol-runtime.workspace = true
qol-config.workspace = true
qol-conventions.workspace = true
qol-apps.workspace = true
serde.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2", features = ["xlib", "xcursor", "xfixes"] }
libc = "0.2"

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
