[package]
name = "task-runner"
version = "1.11.0"
edition = "2021"

[dependencies]
qol-config.workspace = true
qol-conventions.workspace = true
qol-plugin-daemon.workspace = true
qol-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
tempfile = "3.8"
