[package]
name = "plugin-lights"
version = "1.11.1"
edition = "2021"

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
getrandom = "0.2"
serde = { version = "1", features = ["derive"] }
log = "0.4"
qol-conventions.workspace = true
qol-color.workspace = true
qol-config.workspace = true
qol-plugin-daemon.workspace = true
qol-runtime.workspace = true
serde_json = "1"
serialport = { version = "4", default-features = false }
tungstenite = "0.26"

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
