[package]
name = "plugin-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
qol-apps.workspace = true
qol-config.workspace = true
qol-conventions.workspace = true
qol-fs.workspace = true
qol-headless.workspace = true
qol-host-fixes.workspace = true
qol-hotkeys.workspace = true
qol-plugin-daemon.workspace = true
qol-profile-sync.workspace = true
qol-runtime.workspace = true
qol-windowing.workspace = true
serde = { workspace = true }
serde_json.workspace = true
signal-hook = "0.3"

[build-dependencies]
qol-conventions.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
x11rb = { workspace = true, features = ["randr"] }

[dev-dependencies]
qol-plugin-api.workspace = true
tempfile = "3"
