[package]
name = "window-actions"
version = "2.22.4"
edition = "2021"

[dependencies]
qol-apps.workspace = true
qol-config.workspace = true
qol-conventions.workspace = true
qol-fs.workspace = true
qol-headless.workspace = true
qol-platform.workspace = true
qol-plugin-daemon.workspace = true
qol-runtime.workspace = true
qol-windowing.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
proptest = "1"
qol-plugin-api.workspace = true
tempfile = "3"
toml.workspace = true
