use std::fmt::Write;

use qol_color::mix_rgb;

use crate::{
    alt_tab_preview_plane_dark, dark_accent_preset, dark_accent_presets, dark_theme, CssRgba,
    Theme, DARK_REFERENCE, DARK_TRAY_INTERNAL, DARK_TRAY_RAMP, DEV_ACCENT_KEY, PROD_ACCENT_KEY,
};

pub fn dark_css() -> String {
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str(&css_variables(":root", dark_theme()));
    out
}

pub fn tray_css() -> String {
    let mut out = dark_css();
    out.push_str(&tray_variables(":root"));
    out
}

pub fn plugin_lights_css() -> String {
    let mut out = dark_css();
    out.push_str(&plugin_lights_variables(":root", dark_theme()));
    out
}

pub fn plugin_keyremap_css() -> String {
    let mut out = dark_css();
    out.push_str(&plugin_keyremap_variables(":root", dark_theme()));
    out
}

pub fn alt_tab_cinnamon_js() -> String {
    let palette = alt_tab_preview_plane_dark();
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str("module.exports = {\n");
    push_js(&mut out, "backdrop", &clutter_rgba(palette.backdrop_rgba));
    push_js(&mut out, "labelText", &hex6(palette.label_text));
    push_js(&mut out, "cardBg", &clutter_rgba(palette.card_bg_rgba));
    push_js(
        &mut out,
        "cardBorder",
        &clutter_rgba(palette.card_border_rgba),
    );
    push_js(
        &mut out,
        "cardSelectedBg",
        &clutter_rgba(palette.card_selected_bg_rgba),
    );
    push_js(
        &mut out,
        "cardSelectedBorder",
        &clutter_rgba(palette.card_selected_border_rgba),
    );
    out.push_str("};\n");
    out
}

pub fn tray_theme_js() -> String {
    let default = dark_accent_preset(PROD_ACCENT_KEY).expect("default accent exists");
    let tray = DARK_TRAY_INTERNAL;
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str("export const QOL_ACCENT_PRESETS = [\n");
    for preset in dark_accent_presets() {
        let _ = writeln!(
            out,
            "    {{ key: \"{}\", label: \"{}\", rgb: \"{}\", hover: \"{}\" }},",
            preset.key,
            preset.label,
            rgb_string(preset.rgb),
            hex6(preset.hover)
        );
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "export const QOL_DEFAULT_ACCENT = \"{PROD_ACCENT_KEY}\";"
    );
    let _ = writeln!(out, "export const QOL_DEV_ACCENT = \"{DEV_ACCENT_KEY}\";");
    let _ = writeln!(
        out,
        "export const QOL_DEFAULT_ACCENT_RGB = \"{}\";",
        rgb_string(default.rgb)
    );
    out.push_str("export const QOL_TRAY_INTERNAL_COLORS = {\n");
    push_js(&mut out, "dissolveTargetColor", &hex6(tray.dissolve_target));
    push_js(&mut out, "transparentKeyword", "transparent");
    push_js(
        &mut out,
        "transparentRgba",
        &css_rgba_milli(tray.transparent_rgba),
    );
    push_js(
        &mut out,
        "minimapInactiveFill",
        &css_rgba_milli(tray.minimap_inactive_fill),
    );
    push_js(
        &mut out,
        "minimapInactiveStroke",
        &css_rgba_milli(tray.minimap_inactive_stroke),
    );
    push_js(
        &mut out,
        "minimapInactiveText",
        &css_rgba_milli(tray.minimap_inactive_text),
    );
    push_js(
        &mut out,
        "minimapActiveFill",
        &css_rgba_milli(tray.minimap_active_fill),
    );
    push_js(
        &mut out,
        "minimapActiveStroke",
        &css_rgba_milli(tray.minimap_active_stroke),
    );
    push_js(
        &mut out,
        "minimapActiveText",
        &css_rgba_milli(tray.minimap_active_text),
    );
    push_js(&mut out, "configQrDark", &hex6(tray.config_qr_dark));
    push_js(&mut out, "configQrLight", &hex6(tray.config_qr_light));
    push_js(
        &mut out,
        "configLiveColorFallback",
        &hex6(tray.config_live_color_fallback),
    );
    push_js(
        &mut out,
        "configColorThumbStroke",
        &hex6(tray.config_color_thumb_stroke),
    );
    push_js(
        &mut out,
        "configColorThumbShadow",
        &css_rgba_milli(tray.config_color_thumb_shadow),
    );
    out.push_str("};\n");
    out
}

pub fn css_variables(selector: &str, theme: Theme) -> String {
    let palette = theme.system;
    let reference = theme.reference;
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_rgb(&mut out, "qol-system-accent-rgb", palette.accent);
    push_rgb(&mut out, "qol-system-success-rgb", palette.success);
    push_rgb(&mut out, "qol-system-danger-rgb", palette.danger);
    push_rgb(&mut out, "qol-system-info-rgb", palette.info);
    push_rgb(&mut out, "qol-system-warning-rgb", palette.warning);
    push_rgb(&mut out, "qol-system-ink-rgb", reference.black);
    push_rgb(&mut out, "qol-system-paper-rgb", reference.white);
    push_hex(
        &mut out,
        "qol-system-surface-canvas",
        palette.surface_canvas,
    );
    push_hex(
        &mut out,
        "qol-system-surface-elevated",
        palette.surface_elevated,
    );
    push_hex(
        &mut out,
        "qol-system-surface-raised",
        palette.surface_raised,
    );
    push_hex(
        &mut out,
        "qol-system-surface-hovered",
        palette.surface_hovered,
    );
    push_hex(&mut out, "qol-system-text-primary", palette.text_primary);
    push_hex(
        &mut out,
        "qol-system-text-secondary",
        palette.text_secondary,
    );
    push_hex(&mut out, "qol-system-text-muted", palette.text_muted);
    push_hex(&mut out, "qol-system-text-faint", palette.text_faint);
    push_hex(&mut out, "qol-system-border-subtle", palette.border_subtle);
    out.push_str("}\n");
    out
}

fn tray_variables(selector: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_reference_variables(&mut out);
    push_tray_ramp_variables(&mut out);
    push_accent_preset_variables(&mut out);
    out.push_str("}\n");
    out
}

fn push_reference_variables(out: &mut String) {
    push_hex(out, "qol-reference-slate-750", DARK_REFERENCE.slate_750);
    push_hex(out, "qol-reference-slate-600", DARK_REFERENCE.slate_600);
    push_hex(out, "qol-reference-slate-500", DARK_REFERENCE.slate_500);
    push_hex(out, "qol-reference-slate-300", DARK_REFERENCE.slate_300);
    push_hex(out, "qol-reference-slate-100", DARK_REFERENCE.slate_100);
    push_hex(out, "qol-reference-blue-400", DARK_REFERENCE.blue_400);
    push_hex(out, "qol-reference-green-400", DARK_REFERENCE.green_400);
    push_hex(out, "qol-reference-red-500", DARK_REFERENCE.red_500);
    push_hex(out, "qol-reference-amber-500", DARK_REFERENCE.amber_500);
}

fn push_tray_ramp_variables(out: &mut String) {
    push_hex(out, "qol-tray-slate-975", DARK_TRAY_RAMP.slate_975);
    push_hex(out, "qol-tray-slate-950", DARK_TRAY_RAMP.slate_950);
    push_hex(out, "qol-tray-slate-900", DARK_TRAY_RAMP.slate_900);
    push_hex(out, "qol-tray-slate-850", DARK_TRAY_RAMP.slate_850);
    push_hex(out, "qol-tray-slate-800", DARK_TRAY_RAMP.slate_800);
    push_hex(out, "qol-tray-slate-700", DARK_TRAY_RAMP.slate_700);
    push_hex(out, "qol-tray-slate-400", DARK_TRAY_RAMP.slate_400);
    push_hex(out, "qol-tray-slate-200", DARK_TRAY_RAMP.slate_200);
    push_hex(out, "qol-tray-blue-700", DARK_TRAY_RAMP.blue_700);
    push_hex(out, "qol-tray-blue-600", DARK_TRAY_RAMP.blue_600);
    push_hex(out, "qol-tray-blue-500", DARK_TRAY_RAMP.blue_500);
    push_hex(out, "qol-tray-blue-300", DARK_TRAY_RAMP.blue_300);
    push_hex(out, "qol-tray-green-700", DARK_TRAY_RAMP.green_700);
    push_hex(out, "qol-tray-green-600", DARK_TRAY_RAMP.green_600);
    push_hex(out, "qol-tray-green-500", DARK_TRAY_RAMP.green_500);
    push_hex(out, "qol-tray-green-300", DARK_TRAY_RAMP.green_300);
    push_hex(out, "qol-tray-red-700", DARK_TRAY_RAMP.red_700);
    push_hex(out, "qol-tray-red-600", DARK_TRAY_RAMP.red_600);
    push_hex(out, "qol-tray-red-400", DARK_TRAY_RAMP.red_400);
    push_hex(out, "qol-tray-red-300", DARK_TRAY_RAMP.red_300);
    push_hex(out, "qol-tray-amber-700", DARK_TRAY_RAMP.amber_700);
    push_hex(out, "qol-tray-amber-600", DARK_TRAY_RAMP.amber_600);
    push_hex(out, "qol-tray-amber-400", DARK_TRAY_RAMP.amber_400);
    push_hex(out, "qol-tray-amber-300", DARK_TRAY_RAMP.amber_300);
    push_hex(
        out,
        "qol-tray-border-default-2",
        DARK_TRAY_INTERNAL.border_default_2,
    );
    push_hex(
        out,
        "qol-tray-border-strong",
        DARK_TRAY_INTERNAL.border_strong,
    );
    push_hex(
        out,
        "qol-tray-tui-bg-desktop",
        DARK_TRAY_INTERNAL.tui_bg_desktop,
    );
    push_hex(
        out,
        "qol-tray-tui-bg-panel",
        DARK_TRAY_INTERNAL.tui_bg_panel,
    );
    push_hex(
        out,
        "qol-tray-tui-bg-screen",
        DARK_TRAY_INTERNAL.tui_bg_screen,
    );
    push_hex(out, "qol-tray-tui-bg-card", DARK_TRAY_INTERNAL.tui_bg_card);
    push_hex(
        out,
        "qol-atmosphere-wood-bg",
        DARK_TRAY_INTERNAL.atmosphere_wood_bg,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-wood-glow-a",
        DARK_TRAY_INTERNAL.atmosphere_wood_glow_a,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-wood-glow-b",
        DARK_TRAY_INTERNAL.atmosphere_wood_glow_b,
    );
    push_hex(
        out,
        "qol-atmosphere-parchment-bg",
        DARK_TRAY_INTERNAL.atmosphere_parchment_bg,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-parchment-glow-a",
        DARK_TRAY_INTERNAL.atmosphere_parchment_glow_a,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-parchment-glow-b",
        DARK_TRAY_INTERNAL.atmosphere_parchment_glow_b,
    );
    push_hex(
        out,
        "qol-atmosphere-terminal-bg",
        DARK_TRAY_INTERNAL.atmosphere_terminal_bg,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-terminal-glow",
        DARK_TRAY_INTERNAL.atmosphere_terminal_glow,
    );
    push_hex(
        out,
        "qol-atmosphere-spacecraft-bg",
        DARK_TRAY_INTERNAL.atmosphere_spacecraft_bg,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-spacecraft-glow-a",
        DARK_TRAY_INTERNAL.atmosphere_spacecraft_glow_a,
    );
    push_css_rgba(
        out,
        "qol-atmosphere-spacecraft-glow-b",
        DARK_TRAY_INTERNAL.atmosphere_spacecraft_glow_b,
    );
    push_css_rgba(
        out,
        "qol-minimap-inactive-fill",
        DARK_TRAY_INTERNAL.minimap_inactive_fill,
    );
    push_css_rgba(
        out,
        "qol-minimap-inactive-stroke",
        DARK_TRAY_INTERNAL.minimap_inactive_stroke,
    );
    push_css_rgba(
        out,
        "qol-minimap-inactive-text",
        DARK_TRAY_INTERNAL.minimap_inactive_text,
    );
    push_css_rgba(
        out,
        "qol-minimap-active-fill",
        DARK_TRAY_INTERNAL.minimap_active_fill,
    );
    push_css_rgba(
        out,
        "qol-minimap-active-stroke",
        DARK_TRAY_INTERNAL.minimap_active_stroke,
    );
    push_css_rgba(
        out,
        "qol-minimap-active-text",
        DARK_TRAY_INTERNAL.minimap_active_text,
    );
    push_hex(
        out,
        "qol-dissolve-target-color",
        DARK_TRAY_INTERNAL.dissolve_target,
    );
    push_hex(
        out,
        "qol-config-field-thumb-bg",
        DARK_TRAY_INTERNAL.config_field_thumb_bg,
    );
    push_hex(out, "qol-config-qr-dark", DARK_TRAY_INTERNAL.config_qr_dark);
    push_hex(
        out,
        "qol-config-qr-light",
        DARK_TRAY_INTERNAL.config_qr_light,
    );
    push_hex(
        out,
        "qol-config-live-color-fallback",
        DARK_TRAY_INTERNAL.config_live_color_fallback,
    );
    push_hex(
        out,
        "qol-config-color-thumb-stroke",
        DARK_TRAY_INTERNAL.config_color_thumb_stroke,
    );
    push_css_rgba(
        out,
        "qol-config-color-thumb-shadow",
        DARK_TRAY_INTERNAL.config_color_thumb_shadow,
    );
}

fn push_accent_preset_variables(out: &mut String) {
    for preset in dark_accent_presets() {
        push_rgb(out, &format!("qol-accent-{}-rgb", preset.key), preset.rgb);
        push_hex(
            out,
            &format!("qol-accent-{}-hover", preset.key),
            preset.hover,
        );
    }
}

fn plugin_lights_variables(selector: &str, theme: Theme) -> String {
    let reference = theme.reference;
    let system = theme.system;
    let accent_end = mix_rgb(system.accent, reference.black, 0.12);
    let accent_hover = mix_rgb(system.accent, reference.black, 0.06);
    let primary_btn = system.info;
    let primary_btn_hover = mix_rgb(system.info, reference.white, 0.2);

    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_value(
        &mut out,
        "qol-lights-bg-start",
        &hex6(system.surface_raised),
    );
    push_value(
        &mut out,
        "qol-lights-bg-mid",
        &hex6(system.surface_elevated),
    );
    push_value(&mut out, "qol-lights-bg-end", &hex6(system.surface_canvas));
    push_value(
        &mut out,
        "qol-lights-section-bg",
        &css_rgba(system.surface_elevated, 0.8),
    );
    push_value(
        &mut out,
        "qol-lights-text-primary",
        &hex6(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-lights-text-strong",
        &hex6(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-lights-text-secondary",
        &hex6(system.text_secondary),
    );
    push_value(&mut out, "qol-lights-text-muted", &hex6(system.text_muted));
    push_value(&mut out, "qol-lights-text-subtle", &hex6(system.text_muted));
    push_value(&mut out, "qol-lights-text-faint", &hex6(system.text_faint));
    push_value(
        &mut out,
        "qol-lights-text-disabled",
        &hex6(system.text_faint),
    );
    push_value(
        &mut out,
        "qol-lights-text-port-muted",
        &hex6(system.text_secondary),
    );
    push_value(&mut out, "qol-lights-warning", &hex6(system.warning));
    push_value(
        &mut out,
        "qol-lights-warning-glow",
        &css_rgba(system.warning, 0.5),
    );
    push_value(&mut out, "qol-lights-danger", &hex6(system.danger));
    push_value(
        &mut out,
        "qol-lights-danger-glow",
        &css_rgba(system.danger, 0.5),
    );
    push_value(
        &mut out,
        "qol-lights-permission-backdrop",
        &css_rgba(system.surface_canvas, 0.5),
    );
    push_value(
        &mut out,
        "qol-lights-permission-danger-wash",
        &css_rgba(system.danger, 0.18),
    );
    push_value(
        &mut out,
        "qol-lights-permission-card-bg",
        &css_rgba(system.surface_elevated, 0.94),
    );
    push_value(&mut out, "qol-lights-primary-btn", &hex6(primary_btn));
    push_value(
        &mut out,
        "qol-lights-primary-btn-hover",
        &hex6(primary_btn_hover),
    );
    push_value(&mut out, "qol-lights-accent-btn", &hex6(system.accent));
    push_value(&mut out, "qol-lights-accent-btn-hover", &hex6(accent_hover));
    push_value(&mut out, "qol-lights-accent-btn-end", &hex6(accent_end));
    push_value(
        &mut out,
        "qol-lights-accent-btn-shadow",
        &css_rgba(system.accent, 0.3),
    );
    push_value(
        &mut out,
        "qol-lights-wheel-shadow",
        &css_rgba(reference.black, 0.5),
    );
    push_value(
        &mut out,
        "qol-lights-wheel-thumb-stroke",
        &hex6(reference.white),
    );
    push_value(&mut out, "qol-lights-wheel-brightness-floor", "#0a0a0a");
    out.push_str("}\n");
    out
}

fn plugin_keyremap_variables(selector: &str, theme: Theme) -> String {
    let reference = theme.reference;
    let system = theme.system;
    let glow_primary = mix_rgb(system.surface_raised, system.accent, 0.12);
    let glow_secondary = mix_rgb(system.surface_canvas, system.accent, 0.06);
    let border_base = mix_rgb(system.border_subtle, reference.white, 0.4);
    let warning_muted = mix_rgb(system.warning, system.surface_raised, 0.4);
    let save_bg_end = mix_rgb(system.accent, reference.black, 0.12);

    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_value(
        &mut out,
        "qol-keyremap-bg-glow-primary",
        &hex6(glow_primary),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-glow-secondary",
        &hex6(glow_secondary),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-start",
        &hex6(system.surface_canvas),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-mid",
        &hex6(system.surface_raised),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-end",
        &hex6(system.surface_elevated),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-primary",
        &hex6(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-secondary",
        &hex6(system.text_secondary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-heading",
        &hex6(mix_rgb(system.text_primary, system.accent, 0.25)),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-muted",
        &hex6(system.text_secondary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-strong",
        &hex6(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-faint",
        &hex6(system.text_faint),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-tab-muted",
        &hex6(system.text_muted),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-save",
        &hex6(reference.slate_050),
    );
    push_value(
        &mut out,
        "qol-keyremap-card-bg",
        &css_rgba(system.surface_raised, 0.74),
    );
    push_value(
        &mut out,
        "qol-keyremap-card-border",
        &css_rgba(border_base, 0.25),
    );
    push_value(
        &mut out,
        "qol-keyremap-row-bg",
        &css_rgba(system.surface_canvas, 0.6),
    );
    push_value(
        &mut out,
        "qol-keyremap-input-bg",
        &css_rgba(system.surface_canvas, 0.8),
    );
    push_value(
        &mut out,
        "qol-keyremap-dropdown-bg",
        &css_rgba(system.surface_canvas, 0.97),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-subtle",
        &css_rgba(border_base, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-default",
        &css_rgba(border_base, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-muted",
        &css_rgba(border_base, 0.25),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-strong",
        &css_rgba(border_base, 0.35),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-hairline",
        &css_rgba(border_base, 0.08),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-rule",
        &css_rgba(border_base, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-chip-bg",
        &css_rgba(border_base, 0.15),
    );
    push_value(
        &mut out,
        "qol-keyremap-chip-bg-soft",
        &css_rgba(border_base, 0.1),
    );
    push_value(&mut out, "qol-keyremap-accent", &hex6(system.accent));
    push_value(
        &mut out,
        "qol-keyremap-accent-bg",
        &css_rgba(system.accent, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-strong",
        &css_rgba(system.accent, 0.5),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-active",
        &css_rgba(system.accent, 0.4),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-tab",
        &css_rgba(system.accent, 0.25),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-hover",
        &css_rgba(system.accent, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-border",
        &css_rgba(system.accent, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-border-strong",
        &css_rgba(system.accent, 0.35),
    );
    push_value(&mut out, "qol-keyremap-danger", &hex6(system.danger));
    push_value(&mut out, "qol-keyremap-success", &hex6(system.success));
    push_value(
        &mut out,
        "qol-keyremap-success-bg",
        &css_rgba(system.success, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-success-border",
        &css_rgba(system.success, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-border",
        &css_rgba(system.warning, 0.4),
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-bg",
        &css_rgba(system.warning, 0.08),
    );
    push_value(&mut out, "qol-keyremap-warning", &hex6(system.warning));
    push_value(&mut out, "qol-keyremap-warning-muted", &hex6(warning_muted));
    push_value(&mut out, "qol-keyremap-save-bg-start", &hex6(system.accent));
    push_value(&mut out, "qol-keyremap-save-bg-end", &hex6(save_bg_end));
    push_value(
        &mut out,
        "qol-keyremap-shadow",
        &css_rgba(reference.black, 0.4),
    );
    push_value(
        &mut out,
        "qol-keyremap-separator",
        &hex6(system.border_subtle),
    );
    out.push_str("}\n");
    out
}

fn push_hex(out: &mut String, name: &str, color: u32) {
    let _ = writeln!(out, "    --{name}: #{:06x};", color & 0x00ff_ffff);
}

fn push_rgb(out: &mut String, name: &str, color: u32) {
    let (red, green, blue) = rgb_channels(color);
    let _ = writeln!(out, "    --{name}: {red}, {green}, {blue};");
}

fn push_css_rgba(out: &mut String, name: &str, color: CssRgba) {
    push_value(out, name, &css_rgba_milli(color));
}

fn push_value(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "    --{name}: {value};");
}

fn push_js(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "    {name}: \"{value}\",");
}

fn clutter_rgba(color: u32) -> String {
    let red = (color >> 24) & 0xff;
    let green = (color >> 16) & 0xff;
    let blue = (color >> 8) & 0xff;
    let alpha = color & 0xff;
    format!("rgba({red}, {green}, {blue}, {alpha})")
}

fn hex6(color: u32) -> String {
    format!("#{:06x}", color & 0x00ff_ffff)
}

fn css_rgba(color: u32, alpha: f32) -> String {
    let (red, green, blue) = rgb_channels(color);
    format!("rgba({red}, {green}, {blue}, {})", css_alpha(alpha))
}

fn css_rgba_milli(color: CssRgba) -> String {
    let (red, green, blue) = rgb_channels(color.rgb);
    let alpha = color.alpha_milli as f32 / 1000.0;
    format!("rgba({red}, {green}, {blue}, {})", css_alpha(alpha))
}

fn css_alpha(alpha: f32) -> String {
    let formatted = format!("{:.3}", alpha);
    formatted
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}

fn rgb_string(color: u32) -> String {
    let (red, green, blue) = rgb_channels(color);
    format!("{red}, {green}, {blue}")
}

fn rgb_channels(color: u32) -> (u32, u32, u32) {
    ((color >> 16) & 0xff, (color >> 8) & 0xff, color & 0xff)
}
