use std::fmt::Write;

use crate::{
    alt_tab_preview_plane_dark, dark_accent_preset, dark_accent_presets, dark_theme, Theme,
    DARK_REFERENCE, DARK_TRAY_RAMP, DEV_ACCENT_KEY, PROD_ACCENT_KEY,
};

pub fn dark_css() -> String {
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str(&css_variables(":root", dark_theme()));
    out
}

pub fn tray_css() -> String {
    let mut out = dark_css();
    out.push_str(&tray_variables(":root"));
    out
}

pub fn plugin_lights_css() -> String {
    let mut out = dark_css();
    out.push_str(&plugin_lights_variables(":root"));
    out
}

pub fn plugin_keyremap_css() -> String {
    let mut out = dark_css();
    out.push_str(&plugin_keyremap_variables(":root"));
    out
}

pub fn alt_tab_cinnamon_js() -> String {
    let palette = alt_tab_preview_plane_dark();
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str("module.exports = {\n");
    push_js(&mut out, "backdrop", &clutter_rgba(palette.backdrop_rgba));
    push_js(&mut out, "labelText", &hex6(palette.label_text));
    push_js(&mut out, "cardBg", &clutter_rgba(palette.card_bg_rgba));
    push_js(
        &mut out,
        "cardBorder",
        &clutter_rgba(palette.card_border_rgba),
    );
    push_js(
        &mut out,
        "cardSelectedBg",
        &clutter_rgba(palette.card_selected_bg_rgba),
    );
    push_js(
        &mut out,
        "cardSelectedBorder",
        &clutter_rgba(palette.card_selected_border_rgba),
    );
    out.push_str("};\n");
    out
}

pub fn tray_theme_js() -> String {
    let default = dark_accent_preset(PROD_ACCENT_KEY).expect("default accent exists");
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str("export const QOL_ACCENT_PRESETS = [\n");
    for preset in dark_accent_presets() {
        let _ = writeln!(
            out,
            "    {{ key: \"{}\", label: \"{}\", rgb: \"{}\", hover: \"{}\" }},",
            preset.key,
            preset.label,
            rgb_string(preset.rgb),
            hex6(preset.hover)
        );
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "export const QOL_DEFAULT_ACCENT = \"{PROD_ACCENT_KEY}\";"
    );
    let _ = writeln!(out, "export const QOL_DEV_ACCENT = \"{DEV_ACCENT_KEY}\";");
    let _ = writeln!(
        out,
        "export const QOL_DEFAULT_ACCENT_RGB = \"{}\";",
        rgb_string(default.rgb)
    );
    out
}

pub fn css_variables(selector: &str, theme: Theme) -> String {
    let palette = theme.system;
    let reference = theme.reference;
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_rgb(&mut out, "qol-system-accent-rgb", palette.accent);
    push_rgb(&mut out, "qol-system-success-rgb", palette.success);
    push_rgb(&mut out, "qol-system-danger-rgb", palette.danger);
    push_rgb(&mut out, "qol-system-info-rgb", palette.info);
    push_rgb(&mut out, "qol-system-warning-rgb", palette.warning);
    push_rgb(&mut out, "qol-system-ink-rgb", reference.black);
    push_rgb(&mut out, "qol-system-paper-rgb", reference.white);
    push_hex(
        &mut out,
        "qol-system-surface-canvas",
        palette.surface_canvas,
    );
    push_hex(
        &mut out,
        "qol-system-surface-elevated",
        palette.surface_elevated,
    );
    push_hex(
        &mut out,
        "qol-system-surface-raised",
        palette.surface_raised,
    );
    push_hex(
        &mut out,
        "qol-system-surface-hovered",
        palette.surface_hovered,
    );
    push_hex(&mut out, "qol-system-text-primary", palette.text_primary);
    push_hex(
        &mut out,
        "qol-system-text-secondary",
        palette.text_secondary,
    );
    push_hex(&mut out, "qol-system-text-muted", palette.text_muted);
    push_hex(&mut out, "qol-system-text-faint", palette.text_faint);
    push_hex(&mut out, "qol-system-border-subtle", palette.border_subtle);
    out.push_str("}\n");
    out
}

fn tray_variables(selector: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_reference_variables(&mut out);
    push_tray_ramp_variables(&mut out);
    push_accent_preset_variables(&mut out);
    out.push_str("}\n");
    out
}

fn push_reference_variables(out: &mut String) {
    push_hex(out, "qol-reference-slate-750", DARK_REFERENCE.slate_750);
    push_hex(out, "qol-reference-slate-600", DARK_REFERENCE.slate_600);
    push_hex(out, "qol-reference-slate-500", DARK_REFERENCE.slate_500);
    push_hex(out, "qol-reference-slate-300", DARK_REFERENCE.slate_300);
    push_hex(out, "qol-reference-slate-100", DARK_REFERENCE.slate_100);
    push_hex(out, "qol-reference-blue-400", DARK_REFERENCE.blue_400);
    push_hex(out, "qol-reference-green-400", DARK_REFERENCE.green_400);
    push_hex(out, "qol-reference-red-500", DARK_REFERENCE.red_500);
    push_hex(out, "qol-reference-amber-500", DARK_REFERENCE.amber_500);
}

fn push_tray_ramp_variables(out: &mut String) {
    push_hex(out, "qol-tray-slate-975", DARK_TRAY_RAMP.slate_975);
    push_hex(out, "qol-tray-slate-950", DARK_TRAY_RAMP.slate_950);
    push_hex(out, "qol-tray-slate-900", DARK_TRAY_RAMP.slate_900);
    push_hex(out, "qol-tray-slate-850", DARK_TRAY_RAMP.slate_850);
    push_hex(out, "qol-tray-slate-800", DARK_TRAY_RAMP.slate_800);
    push_hex(out, "qol-tray-slate-700", DARK_TRAY_RAMP.slate_700);
    push_hex(out, "qol-tray-slate-400", DARK_TRAY_RAMP.slate_400);
    push_hex(out, "qol-tray-slate-200", DARK_TRAY_RAMP.slate_200);
    push_hex(out, "qol-tray-blue-700", DARK_TRAY_RAMP.blue_700);
    push_hex(out, "qol-tray-blue-600", DARK_TRAY_RAMP.blue_600);
    push_hex(out, "qol-tray-blue-500", DARK_TRAY_RAMP.blue_500);
    push_hex(out, "qol-tray-blue-300", DARK_TRAY_RAMP.blue_300);
    push_hex(out, "qol-tray-green-700", DARK_TRAY_RAMP.green_700);
    push_hex(out, "qol-tray-green-600", DARK_TRAY_RAMP.green_600);
    push_hex(out, "qol-tray-green-500", DARK_TRAY_RAMP.green_500);
    push_hex(out, "qol-tray-green-300", DARK_TRAY_RAMP.green_300);
    push_hex(out, "qol-tray-red-700", DARK_TRAY_RAMP.red_700);
    push_hex(out, "qol-tray-red-600", DARK_TRAY_RAMP.red_600);
    push_hex(out, "qol-tray-red-400", DARK_TRAY_RAMP.red_400);
    push_hex(out, "qol-tray-red-300", DARK_TRAY_RAMP.red_300);
    push_hex(out, "qol-tray-amber-700", DARK_TRAY_RAMP.amber_700);
    push_hex(out, "qol-tray-amber-600", DARK_TRAY_RAMP.amber_600);
    push_hex(out, "qol-tray-amber-400", DARK_TRAY_RAMP.amber_400);
    push_hex(out, "qol-tray-amber-300", DARK_TRAY_RAMP.amber_300);
}

fn push_accent_preset_variables(out: &mut String) {
    for preset in dark_accent_presets() {
        push_rgb(out, &format!("qol-accent-{}-rgb", preset.key), preset.rgb);
        push_hex(
            out,
            &format!("qol-accent-{}-hover", preset.key),
            preset.hover,
        );
    }
}

fn plugin_lights_variables(selector: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_value(&mut out, "qol-lights-bg-start", "#1a1a2e");
    push_value(&mut out, "qol-lights-bg-mid", "#16213e");
    push_value(&mut out, "qol-lights-bg-end", "#0f0f1a");
    push_value(&mut out, "qol-lights-section-bg", "rgba(22, 33, 62, 0.8)");
    push_value(&mut out, "qol-lights-text-primary", "#eeeeee");
    push_value(&mut out, "qol-lights-text-strong", "#e5e7eb");
    push_value(&mut out, "qol-lights-text-secondary", "#bbbbbb");
    push_value(&mut out, "qol-lights-text-muted", "#999999");
    push_value(&mut out, "qol-lights-text-subtle", "#888888");
    push_value(&mut out, "qol-lights-text-faint", "#777777");
    push_value(&mut out, "qol-lights-text-disabled", "#666666");
    push_value(&mut out, "qol-lights-text-port-muted", "#b8bec8");
    push_value(&mut out, "qol-lights-warning", "#fbbf24");
    push_value(
        &mut out,
        "qol-lights-warning-glow",
        "rgba(251, 191, 36, 0.5)",
    );
    push_value(&mut out, "qol-lights-danger", "#f87171");
    push_value(
        &mut out,
        "qol-lights-danger-glow",
        "rgba(248, 113, 113, 0.5)",
    );
    push_value(
        &mut out,
        "qol-lights-permission-backdrop",
        "rgba(6, 8, 18, 0.5)",
    );
    push_value(
        &mut out,
        "qol-lights-permission-danger-wash",
        "rgba(233, 69, 96, 0.18)",
    );
    push_value(
        &mut out,
        "qol-lights-permission-card-bg",
        "rgba(15, 18, 34, 0.94)",
    );
    push_value(&mut out, "qol-lights-primary-btn", "#0f3460");
    push_value(&mut out, "qol-lights-primary-btn-hover", "#154785");
    push_value(&mut out, "qol-lights-accent-btn", "#e94560");
    push_value(&mut out, "qol-lights-accent-btn-hover", "#d63851");
    push_value(&mut out, "qol-lights-accent-btn-end", "#c73550");
    push_value(
        &mut out,
        "qol-lights-accent-btn-shadow",
        "rgba(233, 69, 96, 0.3)",
    );
    push_value(&mut out, "qol-lights-wheel-shadow", "rgba(0, 0, 0, 0.5)");
    push_value(&mut out, "qol-lights-wheel-brightness-floor", "#0a0a0a");
    out.push_str("}\n");
    out
}

fn plugin_keyremap_variables(selector: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_value(&mut out, "qol-keyremap-bg-glow-primary", "#2f3a51");
    push_value(&mut out, "qol-keyremap-bg-glow-secondary", "#1a2937");
    push_value(&mut out, "qol-keyremap-bg-start", "#0b1018");
    push_value(&mut out, "qol-keyremap-bg-mid", "#121a27");
    push_value(&mut out, "qol-keyremap-bg-end", "#0f141f");
    push_value(&mut out, "qol-keyremap-text-primary", "#e8eef9");
    push_value(&mut out, "qol-keyremap-text-secondary", "#a8b7cf");
    push_value(&mut out, "qol-keyremap-text-heading", "#b8cff9");
    push_value(&mut out, "qol-keyremap-text-muted", "#9fb1cf");
    push_value(&mut out, "qol-keyremap-text-strong", "#d7e4ff");
    push_value(&mut out, "qol-keyremap-text-faint", "#5a6a82");
    push_value(&mut out, "qol-keyremap-text-tab-muted", "#7a8ea8");
    push_value(&mut out, "qol-keyremap-text-save", "#f7fbff");
    push_value(&mut out, "qol-keyremap-card-bg", "rgba(14, 22, 35, 0.74)");
    push_value(
        &mut out,
        "qol-keyremap-card-border",
        "rgba(111, 139, 188, 0.25)",
    );
    push_value(&mut out, "qol-keyremap-row-bg", "rgba(8, 14, 24, 0.6)");
    push_value(&mut out, "qol-keyremap-input-bg", "rgba(8, 14, 24, 0.8)");
    push_value(
        &mut out,
        "qol-keyremap-dropdown-bg",
        "rgba(8, 14, 24, 0.97)",
    );
    push_value(
        &mut out,
        "qol-keyremap-border-subtle",
        "rgba(107, 129, 176, 0.2)",
    );
    push_value(
        &mut out,
        "qol-keyremap-border-default",
        "rgba(107, 129, 176, 0.3)",
    );
    push_value(
        &mut out,
        "qol-keyremap-border-muted",
        "rgba(107, 129, 176, 0.25)",
    );
    push_value(
        &mut out,
        "qol-keyremap-border-strong",
        "rgba(107, 129, 176, 0.35)",
    );
    push_value(
        &mut out,
        "qol-keyremap-border-hairline",
        "rgba(107, 129, 176, 0.08)",
    );
    push_value(
        &mut out,
        "qol-keyremap-border-rule",
        "rgba(123, 151, 199, 0.2)",
    );
    push_value(
        &mut out,
        "qol-keyremap-chip-bg",
        "rgba(107, 129, 176, 0.15)",
    );
    push_value(
        &mut out,
        "qol-keyremap-chip-bg-soft",
        "rgba(107, 129, 176, 0.1)",
    );
    push_value(&mut out, "qol-keyremap-accent", "#7db3ff");
    push_value(
        &mut out,
        "qol-keyremap-accent-bg",
        "rgba(63, 120, 223, 0.3)",
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-strong",
        "rgba(63, 120, 223, 0.5)",
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-active",
        "rgba(63, 120, 223, 0.4)",
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-tab",
        "rgba(63, 120, 223, 0.25)",
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-hover",
        "rgba(63, 120, 223, 0.2)",
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-border",
        "rgba(125, 179, 255, 0.3)",
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-border-strong",
        "rgba(125, 179, 255, 0.35)",
    );
    push_value(&mut out, "qol-keyremap-danger", "#ff8989");
    push_value(&mut out, "qol-keyremap-success", "#86d5a3");
    push_value(
        &mut out,
        "qol-keyremap-success-bg",
        "rgba(134, 213, 163, 0.2)",
    );
    push_value(
        &mut out,
        "qol-keyremap-success-border",
        "rgba(134, 213, 163, 0.3)",
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-border",
        "rgba(255, 193, 7, 0.4)",
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-bg",
        "rgba(255, 193, 7, 0.08)",
    );
    push_value(&mut out, "qol-keyremap-warning", "#ffd54f");
    push_value(&mut out, "qol-keyremap-warning-muted", "#bba836");
    push_value(&mut out, "qol-keyremap-save-bg-start", "#3f78df");
    push_value(&mut out, "qol-keyremap-save-bg-end", "#2f57b8");
    push_value(&mut out, "qol-keyremap-shadow", "rgba(0, 0, 0, 0.4)");
    push_value(&mut out, "qol-keyremap-separator", "#3a4a62");
    out.push_str("}\n");
    out
}

fn push_hex(out: &mut String, name: &str, color: u32) {
    let _ = writeln!(out, "    --{name}: #{:06x};", color & 0x00ff_ffff);
}

fn push_rgb(out: &mut String, name: &str, color: u32) {
    let (red, green, blue) = rgb_channels(color);
    let _ = writeln!(out, "    --{name}: {red}, {green}, {blue};");
}

fn push_value(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "    --{name}: {value};");
}

fn push_js(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "    {name}: \"{value}\",");
}

fn clutter_rgba(color: u32) -> String {
    let red = (color >> 24) & 0xff;
    let green = (color >> 16) & 0xff;
    let blue = (color >> 8) & 0xff;
    let alpha = color & 0xff;
    format!("rgba({red}, {green}, {blue}, {alpha})")
}

fn hex6(color: u32) -> String {
    format!("#{:06x}", color & 0x00ff_ffff)
}

fn rgb_string(color: u32) -> String {
    let (red, green, blue) = rgb_channels(color);
    format!("{red}, {green}, {blue}")
}

fn rgb_channels(color: u32) -> (u32, u32, u32) {
    ((color >> 16) & 0xff, (color >> 8) & 0xff, color & 0xff)
}
