pub const ANSI_A: u16 = 0x00;
pub const ANSI_S: u16 = 0x01;
pub const ANSI_D: u16 = 0x02;
pub const ANSI_F: u16 = 0x03;
pub const ANSI_H: u16 = 0x04;
pub const ANSI_G: u16 = 0x05;
pub const ANSI_Z: u16 = 0x06;
pub const ANSI_X: u16 = 0x07;
pub const ANSI_C: u16 = 0x08;
pub const ANSI_V: u16 = 0x09;
pub const ANSI_B: u16 = 0x0B;
pub const ANSI_Q: u16 = 0x0C;
pub const ANSI_W: u16 = 0x0D;
pub const ANSI_E: u16 = 0x0E;
pub const ANSI_R: u16 = 0x0F;
pub const ANSI_Y: u16 = 0x10;
pub const ANSI_T: u16 = 0x11;
pub const ANSI_1: u16 = 0x12;
pub const ANSI_2: u16 = 0x13;
pub const ANSI_3: u16 = 0x14;
pub const ANSI_4: u16 = 0x15;
pub const ANSI_6: u16 = 0x16;
pub const ANSI_5: u16 = 0x17;
pub const ANSI_EQUAL: u16 = 0x18;
pub const ANSI_9: u16 = 0x19;
pub const ANSI_7: u16 = 0x1A;
pub const ANSI_MINUS: u16 = 0x1B;
pub const ANSI_8: u16 = 0x1C;
pub const ANSI_0: u16 = 0x1D;
pub const ANSI_RIGHT_BRACKET: u16 = 0x1E;
pub const ANSI_O: u16 = 0x1F;
pub const ANSI_U: u16 = 0x20;
pub const ANSI_LEFT_BRACKET: u16 = 0x21;
pub const ANSI_I: u16 = 0x22;
pub const ANSI_P: u16 = 0x23;
pub const ANSI_L: u16 = 0x25;
pub const ANSI_J: u16 = 0x26;
pub const ANSI_QUOTE: u16 = 0x27;
pub const ANSI_K: u16 = 0x28;
pub const ANSI_SEMICOLON: u16 = 0x29;
pub const ANSI_BACKSLASH: u16 = 0x2A;
pub const ANSI_COMMA: u16 = 0x2B;
pub const ANSI_SLASH: u16 = 0x2C;
pub const ANSI_N: u16 = 0x2D;
pub const ANSI_M: u16 = 0x2E;
pub const ANSI_PERIOD: u16 = 0x2F;
pub const ANSI_GRAVE: u16 = 0x32;

pub const RETURN: u16 = 0x24;
pub const TAB: u16 = 0x30;
pub const SPACE: u16 = 0x31;
pub const DELETE: u16 = 0x33;
pub const ESCAPE: u16 = 0x35;
pub const FORWARD_DELETE: u16 = 0x75;

pub const LEFT_ARROW: u16 = 0x7B;
pub const RIGHT_ARROW: u16 = 0x7C;
pub const DOWN_ARROW: u16 = 0x7D;
pub const UP_ARROW: u16 = 0x7E;

pub const HOME: u16 = 0x73;
pub const END: u16 = 0x77;
pub const PAGE_UP: u16 = 0x74;
pub const PAGE_DOWN: u16 = 0x79;

pub const F1: u16 = 0x7A;
pub const F2: u16 = 0x78;
pub const F3: u16 = 0x63;
pub const F4: u16 = 0x76;
pub const F5: u16 = 0x60;
pub const F6: u16 = 0x61;
pub const F7: u16 = 0x62;
pub const F8: u16 = 0x64;
pub const F9: u16 = 0x65;
pub const F10: u16 = 0x6D;
pub const F11: u16 = 0x67;
pub const F12: u16 = 0x6F;

pub fn parse_key(name: &str) -> Option<u16> {
    let lower = name.to_ascii_lowercase();
    match lower.as_str() {
        "a" => Some(ANSI_A),
        "b" => Some(ANSI_B),
        "c" => Some(ANSI_C),
        "d" => Some(ANSI_D),
        "e" => Some(ANSI_E),
        "f" => Some(ANSI_F),
        "g" => Some(ANSI_G),
        "h" => Some(ANSI_H),
        "i" => Some(ANSI_I),
        "j" => Some(ANSI_J),
        "k" => Some(ANSI_K),
        "l" => Some(ANSI_L),
        "m" => Some(ANSI_M),
        "n" => Some(ANSI_N),
        "o" => Some(ANSI_O),
        "p" => Some(ANSI_P),
        "q" => Some(ANSI_Q),
        "r" => Some(ANSI_R),
        "s" => Some(ANSI_S),
        "t" => Some(ANSI_T),
        "u" => Some(ANSI_U),
        "v" => Some(ANSI_V),
        "w" => Some(ANSI_W),
        "x" => Some(ANSI_X),
        "y" => Some(ANSI_Y),
        "z" => Some(ANSI_Z),
        "0" => Some(ANSI_0),
        "1" => Some(ANSI_1),
        "2" => Some(ANSI_2),
        "3" => Some(ANSI_3),
        "4" => Some(ANSI_4),
        "5" => Some(ANSI_5),
        "6" => Some(ANSI_6),
        "7" => Some(ANSI_7),
        "8" => Some(ANSI_8),
        "9" => Some(ANSI_9),
        "return" | "enter" => Some(RETURN),
        "tab" => Some(TAB),
        "space" => Some(SPACE),
        "delete" | "backspace" => Some(DELETE),
        "forwarddelete" => Some(FORWARD_DELETE),
        "escape" | "esc" => Some(ESCAPE),
        "left" => Some(LEFT_ARROW),
        "right" => Some(RIGHT_ARROW),
        "down" => Some(DOWN_ARROW),
        "up" => Some(UP_ARROW),
        "home" => Some(HOME),
        "end" => Some(END),
        "pageup" => Some(PAGE_UP),
        "pagedown" => Some(PAGE_DOWN),
        "f1" => Some(F1),
        "f2" => Some(F2),
        "f3" => Some(F3),
        "f4" => Some(F4),
        "f5" => Some(F5),
        "f6" => Some(F6),
        "f7" => Some(F7),
        "f8" => Some(F8),
        "f9" => Some(F9),
        "f10" => Some(F10),
        "f11" => Some(F11),
        "f12" => Some(F12),
        "-" | "minus" => Some(ANSI_MINUS),
        "=" | "equal" | "plus" => Some(ANSI_EQUAL),
        "[" | "leftbracket" => Some(ANSI_LEFT_BRACKET),
        "]" | "rightbracket" => Some(ANSI_RIGHT_BRACKET),
        "\\" | "backslash" => Some(ANSI_BACKSLASH),
        ";" | "semicolon" => Some(ANSI_SEMICOLON),
        "'" | "quote" => Some(ANSI_QUOTE),
        "," | "comma" => Some(ANSI_COMMA),
        "." | "period" => Some(ANSI_PERIOD),
        "/" | "slash" => Some(ANSI_SLASH),
        "`" | "grave" => Some(ANSI_GRAVE),
        _ => None,
    }
}

pub fn key_name(code: u16) -> &'static str {
    match code {
        ANSI_A => "a",
        ANSI_B => "b",
        ANSI_C => "c",
        ANSI_D => "d",
        ANSI_E => "e",
        ANSI_F => "f",
        ANSI_G => "g",
        ANSI_H => "h",
        ANSI_I => "i",
        ANSI_J => "j",
        ANSI_K => "k",
        ANSI_L => "l",
        ANSI_M => "m",
        ANSI_N => "n",
        ANSI_O => "o",
        ANSI_P => "p",
        ANSI_Q => "q",
        ANSI_R => "r",
        ANSI_S => "s",
        ANSI_T => "t",
        ANSI_U => "u",
        ANSI_V => "v",
        ANSI_W => "w",
        ANSI_X => "x",
        ANSI_Y => "y",
        ANSI_Z => "z",
        ANSI_0 => "0",
        ANSI_1 => "1",
        ANSI_2 => "2",
        ANSI_3 => "3",
        ANSI_4 => "4",
        ANSI_5 => "5",
        ANSI_6 => "6",
        ANSI_7 => "7",
        ANSI_8 => "8",
        ANSI_9 => "9",
        RETURN => "return",
        TAB => "tab",
        SPACE => "space",
        DELETE => "delete",
        FORWARD_DELETE => "forwarddelete",
        ESCAPE => "escape",
        LEFT_ARROW => "left",
        RIGHT_ARROW => "right",
        DOWN_ARROW => "down",
        UP_ARROW => "up",
        HOME => "home",
        END => "end",
        PAGE_UP => "pageup",
        PAGE_DOWN => "pagedown",
        F1 => "f1",
        F2 => "f2",
        F3 => "f3",
        F4 => "f4",
        F5 => "f5",
        F6 => "f6",
        F7 => "f7",
        F8 => "f8",
        F9 => "f9",
        F10 => "f10",
        F11 => "f11",
        F12 => "f12",
        ANSI_MINUS => "minus",
        ANSI_EQUAL => "equal",
        ANSI_LEFT_BRACKET => "leftbracket",
        ANSI_RIGHT_BRACKET => "rightbracket",
        ANSI_BACKSLASH => "backslash",
        ANSI_SEMICOLON => "semicolon",
        ANSI_QUOTE => "quote",
        ANSI_COMMA => "comma",
        ANSI_PERIOD => "period",
        ANSI_SLASH => "slash",
        ANSI_GRAVE => "grave",
        _ => "unknown",
    }
}
