[package]
name = "plugin-bluetooth"
version = "0.7.1"
edition = "2021"

[dependencies]
anyhow = "1"
serde.workspace = true
serde_json.workspace = true
qol-apps.workspace = true
qol-config.workspace = true
qol-conventions.workspace = true
qol-headless.workspace = true
qol-runtime.workspace = true

[target.'cfg(unix)'.dependencies]
qol-plugin-daemon.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { version = "0.17.4", features = ["bluetoothd"] }
futures = "0.3"
qol-gpui.workspace = true
qol-process.workspace = true
tokio = { version = "1.35", features = ["process", "rt", "signal", "sync", "time"] }

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
