use std::{collections::HashMap, fmt::Write};

use qol_color::mix_rgb;

use crate::{dark_accent_presets, dark_theme, dark_theme_with_accent_key, Theme};

pub fn dark_css() -> String {
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str(&css_variables(":root", dark_theme()));
    out
}

pub fn plugin_lights_css() -> String {
    plugin_profile_css(plugin_lights_variables)
}

pub fn plugin_keyremap_css() -> String {
    plugin_profile_css(plugin_keyremap_variables)
}

pub fn alt_tab_cinnamon_js() -> String {
    let palette = crate::theme_for_native_key(None, None)
        .components
        .alt_tab_preview_plane;
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str("module.exports = {\n");
    push_js(&mut out, "backdrop", &clutter_rgba(palette.backdrop_rgba));
    push_js(&mut out, "labelText", &hex_string(palette.label_text));
    push_js(&mut out, "cardBg", &clutter_rgba(palette.card_bg_rgba));
    push_js(
        &mut out,
        "cardBorder",
        &clutter_rgba(palette.card_border_rgba),
    );
    push_js(
        &mut out,
        "cardSelectedBg",
        &clutter_rgba(palette.card_selected_bg_rgba),
    );
    push_js(
        &mut out,
        "cardSelectedBorder",
        &clutter_rgba(palette.card_selected_border_rgba),
    );
    out.push_str("};\n");
    out
}

pub fn css_variables(selector: &str, theme: Theme) -> String {
    let palette = theme.system;
    let reference = theme.reference;
    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_rgb(&mut out, "qol-system-accent-rgb", palette.accent);
    push_rgb(&mut out, "qol-system-success-rgb", palette.success);
    push_rgb(&mut out, "qol-system-danger-rgb", palette.danger);
    push_rgb(&mut out, "qol-system-warning-rgb", palette.warning);
    push_rgb(&mut out, "qol-system-ink-rgb", reference.black);
    push_rgb(&mut out, "qol-system-paper-rgb", reference.white);
    push_hex(
        &mut out,
        "qol-system-surface-canvas",
        palette.surface_canvas,
    );
    push_hex(
        &mut out,
        "qol-system-surface-elevated",
        palette.surface_elevated,
    );
    push_hex(
        &mut out,
        "qol-system-surface-raised",
        palette.surface_raised,
    );
    push_hex(
        &mut out,
        "qol-system-surface-hovered",
        palette.surface_hovered,
    );
    push_hex(&mut out, "qol-system-text-primary", palette.text_primary);
    push_hex(
        &mut out,
        "qol-system-text-secondary",
        palette.text_secondary,
    );
    push_hex(&mut out, "qol-system-text-muted", palette.text_muted);
    push_hex(&mut out, "qol-system-text-faint", palette.text_faint);
    push_hex(&mut out, "qol-system-border-subtle", palette.border_subtle);
    out.push_str("}\n");
    out
}

fn plugin_profile_css(component_variables: fn(&str, Theme) -> String) -> String {
    let mut out = plugin_profile_base_css(dark_theme(), component_variables);
    let overrides = accent_override_blocks(&out, component_variables);
    out.push_str(&overrides);
    out
}

fn plugin_profile_base_css(theme: Theme, component_variables: fn(&str, Theme) -> String) -> String {
    let mut out = String::from("/* @generated by qol-theme-css; do not edit by hand. */\n");
    out.push_str(&css_variables(":root", theme));
    out.push_str(&component_variables(":root", theme));
    out
}

fn accent_override_blocks(base: &str, component_variables: fn(&str, Theme) -> String) -> String {
    let base_variables = css_variable_map(base);
    let mut out = String::new();

    for preset in dark_accent_presets() {
        let variant =
            plugin_profile_base_css(dark_theme_with_accent_key(preset.key), component_variables);
        let diff = css_variable_diff(&base_variables, &variant);
        if diff.is_empty() {
            continue;
        }
        let _ = writeln!(out, ":root[data-qol-accent=\"{}\"] {{", preset.key);
        for (name, value) in diff {
            let _ = writeln!(out, "    {name}: {value};");
        }
        out.push_str("}\n");
    }

    out
}

fn css_variable_diff(
    base_variables: &HashMap<String, String>,
    variant_css: &str,
) -> Vec<(String, String)> {
    css_variable_entries(variant_css)
        .into_iter()
        .filter(|(name, value)| base_variables.get(name) != Some(value))
        .collect()
}

fn css_variable_map(css: &str) -> HashMap<String, String> {
    css_variable_entries(css).into_iter().collect()
}

fn css_variable_entries(css: &str) -> Vec<(String, String)> {
    css.lines().filter_map(css_variable_entry).collect()
}

fn css_variable_entry(line: &str) -> Option<(String, String)> {
    let line = line.trim();
    if !line.starts_with("--") {
        return None;
    }
    let (name, value) = line.split_once(':')?;
    Some((
        name.to_string(),
        value.trim().trim_end_matches(';').to_string(),
    ))
}

fn plugin_lights_variables(selector: &str, theme: Theme) -> String {
    let reference = theme.reference;
    let system = theme.system;
    let accent_end = mix_rgb(system.accent, reference.black, 0.12);
    let accent_hover = mix_rgb(system.accent, reference.black, 0.06);
    let primary_btn = system.info;
    let primary_btn_hover = mix_rgb(system.info, reference.white, 0.2);

    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_value(
        &mut out,
        "qol-lights-bg-start",
        &hex_string(system.surface_raised),
    );
    push_value(
        &mut out,
        "qol-lights-bg-mid",
        &hex_string(system.surface_elevated),
    );
    push_value(
        &mut out,
        "qol-lights-bg-end",
        &hex_string(system.surface_canvas),
    );
    push_value(
        &mut out,
        "qol-lights-section-bg",
        &css_rgba(system.surface_elevated, 0.8),
    );
    push_value(
        &mut out,
        "qol-lights-text-primary",
        &hex_string(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-lights-text-strong",
        &hex_string(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-lights-text-secondary",
        &hex_string(system.text_secondary),
    );
    push_value(
        &mut out,
        "qol-lights-text-muted",
        &hex_string(system.text_muted),
    );
    push_value(
        &mut out,
        "qol-lights-text-subtle",
        &hex_string(system.text_muted),
    );
    push_value(
        &mut out,
        "qol-lights-text-faint",
        &hex_string(system.text_faint),
    );
    push_value(
        &mut out,
        "qol-lights-text-disabled",
        &hex_string(system.text_faint),
    );
    push_value(
        &mut out,
        "qol-lights-text-port-muted",
        &hex_string(system.text_secondary),
    );
    push_value(&mut out, "qol-lights-warning", &hex_string(system.warning));
    push_value(
        &mut out,
        "qol-lights-warning-glow",
        &css_rgba(system.warning, 0.5),
    );
    push_value(&mut out, "qol-lights-danger", &hex_string(system.danger));
    push_value(
        &mut out,
        "qol-lights-danger-glow",
        &css_rgba(system.danger, 0.5),
    );
    push_value(
        &mut out,
        "qol-lights-permission-backdrop",
        &css_rgba(system.surface_canvas, 0.5),
    );
    push_value(
        &mut out,
        "qol-lights-permission-danger-wash",
        &css_rgba(system.danger, 0.18),
    );
    push_value(
        &mut out,
        "qol-lights-permission-card-bg",
        &css_rgba(system.surface_elevated, 0.94),
    );
    push_value(&mut out, "qol-lights-primary-btn", &hex_string(primary_btn));
    push_value(
        &mut out,
        "qol-lights-primary-btn-hover",
        &hex_string(primary_btn_hover),
    );
    push_value(
        &mut out,
        "qol-lights-accent-btn",
        &hex_string(system.accent),
    );
    push_value(
        &mut out,
        "qol-lights-accent-btn-hover",
        &hex_string(accent_hover),
    );
    push_value(
        &mut out,
        "qol-lights-accent-btn-end",
        &hex_string(accent_end),
    );
    push_value(
        &mut out,
        "qol-lights-accent-btn-shadow",
        &css_rgba(system.accent, 0.3),
    );
    push_value(
        &mut out,
        "qol-lights-wheel-shadow",
        &css_rgba(reference.black, 0.5),
    );
    push_value(
        &mut out,
        "qol-lights-wheel-thumb-stroke",
        &hex_string(reference.white),
    );
    push_value(&mut out, "qol-lights-wheel-brightness-floor", "#0a0a0a");
    out.push_str("}\n");
    out
}

fn plugin_keyremap_variables(selector: &str, theme: Theme) -> String {
    let reference = theme.reference;
    let system = theme.system;
    let glow_primary = mix_rgb(system.surface_raised, system.accent, 0.12);
    let glow_secondary = mix_rgb(system.surface_canvas, system.accent, 0.06);
    let border_base = mix_rgb(system.border_subtle, reference.white, 0.4);
    let warning_muted = mix_rgb(system.warning, system.surface_raised, 0.4);
    let save_bg_end = mix_rgb(system.accent, reference.black, 0.12);

    let mut out = String::new();
    let _ = writeln!(out, "{selector} {{");
    push_value(
        &mut out,
        "qol-keyremap-bg-glow-primary",
        &hex_string(glow_primary),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-glow-secondary",
        &hex_string(glow_secondary),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-start",
        &hex_string(system.surface_canvas),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-mid",
        &hex_string(system.surface_raised),
    );
    push_value(
        &mut out,
        "qol-keyremap-bg-end",
        &hex_string(system.surface_elevated),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-primary",
        &hex_string(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-secondary",
        &hex_string(system.text_secondary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-heading",
        &hex_string(mix_rgb(system.text_primary, system.accent, 0.25)),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-muted",
        &hex_string(system.text_secondary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-strong",
        &hex_string(system.text_primary),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-faint",
        &hex_string(system.text_faint),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-tab-muted",
        &hex_string(system.text_muted),
    );
    push_value(
        &mut out,
        "qol-keyremap-text-save",
        &hex_string(reference.slate_050),
    );
    push_value(
        &mut out,
        "qol-keyremap-card-bg",
        &css_rgba(system.surface_raised, 0.74),
    );
    push_value(
        &mut out,
        "qol-keyremap-card-border",
        &css_rgba(border_base, 0.25),
    );
    push_value(
        &mut out,
        "qol-keyremap-row-bg",
        &css_rgba(system.surface_canvas, 0.6),
    );
    push_value(
        &mut out,
        "qol-keyremap-input-bg",
        &css_rgba(system.surface_canvas, 0.8),
    );
    push_value(
        &mut out,
        "qol-keyremap-dropdown-bg",
        &css_rgba(system.surface_canvas, 0.97),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-subtle",
        &css_rgba(border_base, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-default",
        &css_rgba(border_base, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-muted",
        &css_rgba(border_base, 0.25),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-strong",
        &css_rgba(border_base, 0.35),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-hairline",
        &css_rgba(border_base, 0.08),
    );
    push_value(
        &mut out,
        "qol-keyremap-border-rule",
        &css_rgba(border_base, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-chip-bg",
        &css_rgba(border_base, 0.15),
    );
    push_value(
        &mut out,
        "qol-keyremap-chip-bg-soft",
        &css_rgba(border_base, 0.1),
    );
    push_value(&mut out, "qol-keyremap-accent", &hex_string(system.accent));
    push_value(
        &mut out,
        "qol-keyremap-accent-bg",
        &css_rgba(system.accent, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-strong",
        &css_rgba(system.accent, 0.5),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-active",
        &css_rgba(system.accent, 0.4),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-tab",
        &css_rgba(system.accent, 0.25),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-bg-hover",
        &css_rgba(system.accent, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-border",
        &css_rgba(system.accent, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-accent-border-strong",
        &css_rgba(system.accent, 0.35),
    );
    push_value(&mut out, "qol-keyremap-danger", &hex_string(system.danger));
    push_value(
        &mut out,
        "qol-keyremap-success",
        &hex_string(system.success),
    );
    push_value(
        &mut out,
        "qol-keyremap-success-bg",
        &css_rgba(system.success, 0.2),
    );
    push_value(
        &mut out,
        "qol-keyremap-success-border",
        &css_rgba(system.success, 0.3),
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-border",
        &css_rgba(system.warning, 0.4),
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-bg",
        &css_rgba(system.warning, 0.08),
    );
    push_value(
        &mut out,
        "qol-keyremap-warning",
        &hex_string(system.warning),
    );
    push_value(
        &mut out,
        "qol-keyremap-warning-muted",
        &hex_string(warning_muted),
    );
    push_value(
        &mut out,
        "qol-keyremap-save-bg-start",
        &hex_string(system.accent),
    );
    push_value(
        &mut out,
        "qol-keyremap-save-bg-end",
        &hex_string(save_bg_end),
    );
    push_value(
        &mut out,
        "qol-keyremap-shadow",
        &css_rgba(reference.black, 0.4),
    );
    push_value(
        &mut out,
        "qol-keyremap-separator",
        &hex_string(system.border_subtle),
    );
    out.push_str("}\n");
    out
}

fn push_hex(out: &mut String, name: &str, color: u32) {
    let _ = writeln!(out, "    --{name}: #{:06x};", color & 0x00ff_ffff);
}

fn push_rgb(out: &mut String, name: &str, color: u32) {
    let (red, green, blue) = rgb_channels(color);
    let _ = writeln!(out, "    --{name}: {red}, {green}, {blue};");
}

fn push_value(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "    --{name}: {value};");
}

fn push_js(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "    {name}: \"{value}\",");
}

fn clutter_rgba(color: u32) -> String {
    let red = (color >> 24) & 0xff;
    let green = (color >> 16) & 0xff;
    let blue = (color >> 8) & 0xff;
    let alpha = color & 0xff;
    format!("rgba({red}, {green}, {blue}, {alpha})")
}

pub fn hex_string(color: u32) -> String {
    format!("#{:06x}", color & 0x00ff_ffff)
}

fn css_rgba(color: u32, alpha: f32) -> String {
    let (red, green, blue) = rgb_channels(color);
    format!("rgba({red}, {green}, {blue}, {})", css_alpha(alpha))
}

fn css_alpha(alpha: f32) -> String {
    let formatted = format!("{:.3}", alpha);
    formatted
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}

pub fn rgb_string(color: u32) -> String {
    let (red, green, blue) = rgb_channels(color);
    format!("{red}, {green}, {blue}")
}

fn rgb_channels(color: u32) -> (u32, u32, u32) {
    ((color >> 16) & 0xff, (color >> 8) & 0xff, color & 0xff)
}
