[package]
name = "qol-memory"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1"
flate2 = "1"
gethostname = "1.1"
regex = "1"
sha1 = "0.10"
sha2.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["float_roundtrip", "preserve_order"] }
ureq = { version = "2", features = ["json"] }
qol-agent-homes.workspace = true
qol-config.workspace = true
qol-conventions.workspace = true
qol-fs.workspace = true
qol-headless.workspace = true
qol-plugin-daemon.workspace = true
qol-process.workspace = true
qol-runtime.workspace = true
qol-watch.workspace = true
workspace-hack.workspace = true

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
