[package]
name = "plugin-lights"
version = "1.24.0"
edition = "2021"

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
getrandom = "0.3"
serde.workspace = true
log = "0.4"
qol-apps.workspace = true
qol-conventions.workspace = true
qol-color.workspace = true
qol-config.workspace = true
qol-headless.workspace = true
qol-plugin-daemon.workspace = true
qol-runtime.workspace = true
serde_json.workspace = true
serialport = { version = "4", default-features = false }
tungstenite = "0.26"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2"

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
tempfile = "3"
