[package]
name = "qol-shot"
version = "1.51.0"
edition = "2021"

[dependencies]
anyhow = "1"
qol-apps.workspace = true
qol-color.workspace = true
qol-config.workspace = true
qol-conventions.workspace = true
qol-fs.workspace = true
qol-headless.workspace = true
qol-process.workspace = true
qol-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock"] }
futures = "0.3"
image = { version = "0.25", default-features = false, features = ["png"] }
gpui.workspace = true
qol-gpui.workspace = true
qol-platform.workspace = true
smallvec = "1.13"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
qol-plugin-daemon.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { workspace = true, features = ["shm", "xfixes"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
objc2.workspace = true

[build-dependencies]
qol-conventions.workspace = true

[dev-dependencies]
qol-plugin-api.workspace = true
